require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/m/payment_methods", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # M::PaymentMethod. As you add validations to M::PaymentMethod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      M::PaymentMethod.create! valid_attributes
      get m_payment_methods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      payment_method = M::PaymentMethod.create! valid_attributes
      get m_payment_method_url(payment_method)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_m_payment_method_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      payment_method = M::PaymentMethod.create! valid_attributes
      get edit_m_payment_method_url(payment_method)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new M::PaymentMethod" do
        expect {
          post m_payment_methods_url, params: { m_payment_method: valid_attributes }
        }.to change(M::PaymentMethod, :count).by(1)
      end

      it "redirects to the created m_payment_method" do
        post m_payment_methods_url, params: { m_payment_method: valid_attributes }
        expect(response).to redirect_to(m_payment_method_url(M::PaymentMethod.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new M::PaymentMethod" do
        expect {
          post m_payment_methods_url, params: { m_payment_method: invalid_attributes }
        }.to change(M::PaymentMethod, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post m_payment_methods_url, params: { m_payment_method: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested m_payment_method" do
        payment_method = M::PaymentMethod.create! valid_attributes
        patch m_payment_method_url(payment_method), params: { m_payment_method: new_attributes }
        payment_method.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the m_payment_method" do
        payment_method = M::PaymentMethod.create! valid_attributes
        patch m_payment_method_url(payment_method), params: { m_payment_method: new_attributes }
        payment_method.reload
        expect(response).to redirect_to(m_payment_method_url(payment_method))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        payment_method = M::PaymentMethod.create! valid_attributes
        patch m_payment_method_url(payment_method), params: { m_payment_method: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested m_payment_method" do
      payment_method = M::PaymentMethod.create! valid_attributes
      expect {
        delete m_payment_method_url(payment_method)
      }.to change(M::PaymentMethod, :count).by(-1)
    end

    it "redirects to the m_payment_methods list" do
      payment_method = M::PaymentMethod.create! valid_attributes
      delete m_payment_method_url(payment_method)
      expect(response).to redirect_to(m_payment_methods_url)
    end
  end
end
